name: GKS Think Tank Project Proposal
description: GKS Think Tank Project Proposal
title: "[Project title]"
labels: [GKS Think Tank]

body:
  - type: input
    id: submitter_name
    attributes:
      label: Submitter Name
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: submitter_affiliation
    attributes:
      label: Submitter Affiliation
      placeholder: ABC Institution
    validations:
      required: false
  - type: textarea
    id: project_details
    attributes:
      label: Project Details
      description: Discuss what the project intends to accomplish and how it improves the use of GKS
    validations:
      required: true
  - type: textarea
    id: required_maintainers
    attributes:
      label: Required Maintainer(s) Attendance
      description: Does this project require specific maintainer(s) to attend? If yes, please list their GitHub handles below.
    validations:
      required: false
  - type: textarea
    id: required_skills
    attributes:
      label: Required Skills
      description: List any skillset necessary or beneficial for participants to contribute to the project, e.g. Python, reStructuredText, Rust, UML
    validations:
      required: true
